// This file is generated by Slice Machine. Update with care!

import JumboTron from './JumboTron';
import Service from './Service';
import Testimonial from './Testimonial';

export {
	JumboTron,
	Service,
	Testimonial,
};

export const components = {
	jumbo_tron: JumboTron,
	service: Service,
	testimonial: Testimonial,
};
