// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import JumboTron from './JumboTron';
import Testimonial from './Testimonial';

export {
	CallToAction,
	JumboTron,
	Testimonial,
};

export const components = {
	call_to_action: CallToAction,
	jumbo_tron: JumboTron,
	testimonial: Testimonial,
};
